import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,newUser,apartmentInput,status} from './helpers.mjs';
import * as D from '../server/domain.mjs';import {ensureMaxUser} from '../server/auth.mjs';
import {makeMessage,deepLink,botLink,enqueueUpdate,processInbox} from '../server/bot.mjs';

test('Deep links use configurable HTTPS host and distinguish Bot start from Mini App startapp',t=>{const f=fixture(t),c={...f.config,botUsername:'test_bot',deepLinkBase:'https://max.example.test'};assert.equal(botLink(c,'join_abc'),'https://max.example.test/test_bot?start=join_abc');assert.equal(deepLink(c,'r_123'),'https://max.example.test/test_bot?startapp=r_123');assert.equal(deepLink(c,'c_123'),'https://max.example.test/test_bot?startapp=c_123');});
test('Comment notification includes author and text, links directly to discussion and escapes HTML',t=>{const f=fixture(t);const r=f.create('ticket',{description:'Кран',room:'Кухня'});f.db.tx(()=>D.addComment(f.db,f.owner,r.id,{text:'Ответ <script> & проверка'}));const n=f.db.get('SELECT * FROM notifications WHERE user_id=? ORDER BY rowid DESC LIMIT 1',f.tenant.id);assert.ok(n.title.includes(f.owner.name));assert.ok(n.text.includes('Ответ <script>'));const message=makeMessage(f.db,{...f.config,botUsername:'test_bot'},f.tenant.id,{...n,recordId:r.id,discussion:true});assert.equal(message.format,'html');assert.ok(message.text.includes('&lt;script&gt;'));assert.ok(!message.text.includes('<script>'));assert.equal(message.attachments[0].payload.buttons.at(-1)[0].text,'Ответить в обсуждении');assert.ok(message.attachments[0].payload.buttons.at(-1)[0].url.includes('startapp=c_'));});
test('Long escaped message remains below 4000 characters with complete HTML entities',t=>{const f=fixture(t),m=makeMessage(f.db,f.config,f.tenant.id,{title:'&'.repeat(300),text:'<>&'.repeat(3000)});assert.ok(m.text.length<4000);assert.match(m.text,/^<b>/);assert.ok(!/&(?!amp;|lt;|gt;)/.test(m.text));});
test('Invitation Bot start only previews; acceptance binds lease then opens Mini App; callback replay is idempotent',t=>{const f=fixture(t),a=f.db.tx(()=>D.createApartment(f.db,f.owner,apartmentInput)),l=f.db.get('SELECT * FROM leases WHERE apartment_id=?',a.id),i=f.db.tx(()=>D.createInvite(f.db,f.owner,l.id));const source={user_id:98765,name:'Новый Жилец'};enqueueUpdate(f.db,{update_type:'bot_started',timestamp:1,user:source,payload:'join_'+i.code});processInbox(f.db);const u=f.db.get('SELECT * FROM users WHERE max_id=?','98765');assert.equal(u.name,source.name);assert.ok(!D.isMember(f.db,u.id,l.id));const b=JSON.parse(f.db.get('SELECT body FROM outbox WHERE user_id=? ORDER BY rowid DESC LIMIT 1',u.id).body);assert.equal(b.inviteCode,i.code);const msg=makeMessage(f.db,f.config,u.id,b);assert.equal(msg.attachments[0].payload.buttons[0][0].payload,'join|'+i.code);const cb={update_type:'message_callback',callback:{callback_id:'join-callback',user:source,payload:'join|'+i.code}};enqueueUpdate(f.db,cb);processInbox(f.db);assert.ok(D.isMember(f.db,u.id,l.id));let response=JSON.parse(f.db.get('SELECT body FROM outbox WHERE user_id=? ORDER BY rowid DESC LIMIT 1',u.id).body);assert.equal(response.target,'l_'+l.id);enqueueUpdate(f.db,cb);processInbox(f.db);assert.equal(D.memberIds(f.db,l.id).length,1);});
test('Invitation forwarded to a group does not register private membership there',t=>{const f=fixture(t);enqueueUpdate(f.db,{update_type:'message_created',message:{body:{mid:'group-start',text:'/start join_secret'},sender:{user_id:7777,name:'Group'},recipient:{chat_type:'chat',chat_id:99}}});processInbox(f.db);assert.equal(f.db.get("SELECT status FROM webhook_inbox WHERE id='msg:group-start'").status,'ignored');assert.equal(f.db.get('SELECT * FROM users WHERE max_id=?','7777'),undefined);});
test('Unknown/foreign record notification never exposes stale private title or text',t=>{const f=fixture(t),r=f.create('ticket',{room:'Кухня',description:'Секрет'});const m=makeMessage(f.db,f.config,f.other.id,{title:'Секрет',text:'Личные данные',recordId:r.id});assert.ok(!m.text.includes('Секрет'));assert.ok(!m.text.includes('Личные данные'));});
