import test from 'node:test';import assert from 'node:assert/strict';
import {fixture} from './helpers.mjs';
import {enqueueUpdate,processInbox,processOutbox,makeMessage} from '../server/bot.mjs';
import * as D from '../server/domain.mjs';
function linked(f){f.db.run("UPDATE users SET max_id='12345',bot_enabled=1 WHERE id='demo-tenant'");f.db.run("UPDATE users SET max_id='54321',bot_enabled=1 WHERE id='demo-owner'");}
test('Bot: duplicate /start processed once; group messages ignored',t=>{const f=fixture(t),event={update_type:'message_created',message:{body:{mid:'message-1',text:'/start'},sender:{user_id:900,first_name:'Тест'},recipient:{chat_type:'dialog'}}};enqueueUpdate(f.db,event);enqueueUpdate(f.db,event);processInbox(f.db);assert.equal(f.db.get('SELECT COUNT(*) AS n FROM outbox').n,1);enqueueUpdate(f.db,{...event,message:{...event.message,body:{mid:'group-1',text:'/start'},recipient:{chat_type:'chat'}}});processInbox(f.db);assert.equal(f.db.get('SELECT COUNT(*) AS n FROM outbox').n,1);});
test('Bot: callback authentic actor accepts once; stale callback cannot repeat',t=>{const f=fixture(t);linked(f);const visit=D.bootstrap(f.db,f.tenant,f.config).records.find(x=>x.kind==='visit');const event={update_type:'message_callback',callback:{callback_id:'cb1',user:{user_id:12345,first_name:'Илья'},payload:`visit|${visit.id}|${visit.version}|accept`}};enqueueUpdate(f.db,event);enqueueUpdate(f.db,event);processInbox(f.db);assert.equal(f.db.get('SELECT status FROM records WHERE id=?',visit.id).status,'accepted');assert.equal(f.db.get('SELECT version FROM records WHERE id=?',visit.id).version,visit.version+1);enqueueUpdate(f.db,{...event,callback:{...event.callback,callback_id:'cb2'}});processInbox(f.db);assert.equal(f.db.get('SELECT version FROM records WHERE id=?',visit.id).version,visit.version+1);});
test('Bot: unrelated callback user cannot accept private visit',t=>{const f=fixture(t),visit=D.bootstrap(f.db,f.tenant,f.config).records.find(x=>x.kind==='visit');enqueueUpdate(f.db,{update_type:'message_callback',callback:{callback_id:'foreign',user:{user_id:9000,first_name:'Не участник'},payload:`visit|${visit.id}|${visit.version}|accept`}});processInbox(f.db);assert.equal(f.db.get('SELECT status FROM records WHERE id=?',visit.id).status,'proposed');});
test('Bot: notification buttons are contextual and deep link to record',t=>{const f=fixture(t),r=D.bootstrap(f.db,f.tenant,f.config).records.find(x=>x.kind==='visit');f.config.botUsername='keys_test';const msg=makeMessage(f.db,f.config,f.tenant.id,{title:'Визит',recordId:r.id});assert.equal(msg.attachments[0].payload.buttons[0][0].type,'callback');assert.match(msg.attachments[0].payload.buttons[1][0].url,/startapp=r_/);});
test('Bot: outbox respects notification opt-out even after queueing',async t=>{const f=fixture(t);linked(f);D.pushNotification(f.db,f.tenant.id,'Test','Text',null,null,'events');f.db.run("UPDATE users SET settings=? WHERE id=?",JSON.stringify({bot:false}),f.tenant.id);const before=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw Error('Must not call MAX');};t.after(()=>globalThis.fetch=before);await processOutbox(f.db,f.config);assert.equal(calls,0);assert.equal(f.db.get('SELECT status FROM outbox').status,'skipped');});
test('Bot: API failure persisted and retried; auth token not in URL',async t=>{const f=fixture(t);linked(f);D.pushNotification(f.db,f.tenant.id,'Test','Text');let seen;const before=globalThis.fetch;globalThis.fetch=async(url,options)=>{seen={url,options};return {ok:false,status:503,json:async()=>({code:'unavailable'})};};t.after(()=>globalThis.fetch=before);await processOutbox(f.db,f.config);const row=f.db.get('SELECT * FROM outbox');assert.equal(row.status,'queued');assert.equal(row.attempts,1);assert.ok(row.next_attempt>Date.now());assert.equal(seen.options.headers.Authorization,'test-token');assert.ok(!seen.url.includes('test-token'));});
test('Bot: /stop and /notifications change preferences',t=>{const f=fixture(t);linked(f);for(const [command,expected]of[['/stop',false],['/notifications',true]]){enqueueUpdate(f.db,{update_type:'message_created',message:{sender:{user_id:12345,first_name:'Илья'},recipient:{chat_type:'dialog'},body:{mid:command,text:command}}});processInbox(f.db);assert.equal(D.settings(f.u(f.tenant.id)).bot,expected);}});
