import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,newUser,apartmentInput,status} from './helpers.mjs';import * as D from '../server/domain.mjs';
const Y=new Date().getUTCFullYear()+1;
const date=(suffix)=>`${Y}-${suffix}`,at=s=>Date.parse(s+'T12:00:00Z');
function setup(f,{due=31,auto=false}={}){const a=f.db.tx(()=>D.createApartment(f.db,f.owner,{...apartmentInput,start:date('01-01'),end:`${Y+1}-12-31`,recurring_rent:auto,due_day:due})),l=f.db.get('SELECT * FROM leases WHERE apartment_id=?',a.id),u=newUser(f.db,'Жилец');const i=f.db.tx(()=>D.createInvite(f.db,f.owner,l.id));f.db.tx(()=>D.joinInvite(f.db,u,i.code));return {a,l,u};}
const run=(f,d)=>f.db.tx(()=>D.generateRecurring(f.db,f.config,at(d)));
const list=(f,l)=>f.db.all("SELECT * FROM records WHERE lease_id=? AND kind='charge' ORDER BY json_extract(payload,'$.due')",l.id).map(D.decode);
const rule=(f,l,extra={})=>f.db.tx(()=>D.createRecurringRule(f.db,f.owner,{lease_id:l.id,title:'Интернет',amount:90000,due_day:31,advance_days:14,start_month:date('01'),...extra},f.config));
const edit=(f,r,body)=>f.db.tx(()=>D.updateRecurringRule(f.db,f.owner,r.id,{version:f.db.get('SELECT version FROM recurring_rules WHERE id=?',r.id).version,...body},f.config));
test('Recurring bill appears 14 days in advance, stays idempotent and does not multiply by tenants',t=>{const f=fixture(t),{l}=setup(f);rule(f,l);run(f,date('01-16'));assert.equal(list(f,l).length,0);run(f,date('01-17'));assert.equal(list(f,l).length,1);assert.equal(list(f,l)[0].payload.due,date('01-31'));run(f,date('01-17'));assert.equal(list(f,l).length,1);run(f,date('01-31'));assert.equal(list(f,l).length,1);});
test('Short month and leap year clamp requested day 31 without JS date overflow',t=>{assert.equal(D.dueDate('2027-02',31),'2027-02-28');assert.equal(D.dueDate('2028-02',31),'2028-02-29');assert.equal(D.dueDate('2027-04',31),'2027-04-30');const f=fixture(t),{l}=setup(f);rule(f,l);run(f,date('02-28'));assert.equal(list(f,l).find(r=>r.payload.period===date('02')).payload.due,D.dueDate(date('02'),31));});
test('Future change retains invoice history and keeps January frozen',t=>{const f=fixture(t),{l}=setup(f),r=rule(f,l);run(f,date('01-20'));const jan=list(f,l)[0];assert.throws(()=>edit(f,r,{effective_month:date('01'),amount:100000}),status(409));edit(f,r,{effective_month:date('02'),amount:110000,due_day:10});run(f,date('01-28'));const rr=list(f,l);assert.equal(rr.find(x=>x.id===jan.id).payload.amount,90000);assert.equal(rr.find(x=>x.payload.period===date('02')).payload.amount,110000);assert.equal(rr.find(x=>x.payload.period===date('02')).payload.due,date('02-10'));});
test('Pause and resume skip paused months, deletion retains unpaid invoice history',t=>{const f=fixture(t),{l}=setup(f),r=rule(f,l);run(f,date('01-20'));edit(f,r,{action:'pause'});run(f,date('02-28'));assert.equal(list(f,l).length,1);edit(f,r,{action:'resume',effective_month:date('03')});run(f,date('03-20'));assert.deepEqual(list(f,l).map(r=>r.payload.period),[date('01'),date('03')]);edit(f,r,{action:'delete'});run(f,date('04-30'));assert.equal(list(f,l).length,2);assert.equal(f.db.get('SELECT state FROM recurring_rules WHERE id=?',r.id).state,'deleted');});
test('Rule creation validates range, advance window and owner access',t=>{const f=fixture(t),{l,u}=setup(f);assert.throws(()=>rule(f,l,{advance_days:0}),status(400));assert.throws(()=>rule(f,l,{advance_days:61}),status(400));assert.throws(()=>rule(f,l,{due_day:32}),status(400));assert.throws(()=>rule(f,l,{end_month:date('00')}),status(400));assert.throws(()=>D.createRecurringRule(f.db,u,{lease_id:l.id}),status(404));});
test('Recurring changes use optimistic version and cannot backdate beyond an existing future invoice',t=>{const f=fixture(t),{l}=setup(f),r=rule(f,l);edit(f,r,{effective_month:date('02'),title:'Связь'});assert.throws(()=>D.updateRecurringRule(f.db,f.owner,r.id,{version:1,action:'pause'},f.config),status(409));run(f,date('04-29'));assert.throws(()=>edit(f,r,{effective_month:date('02'),amount:3}),status(409));assert.equal(D.nextEditableMonth(f.db,f.db.get('SELECT * FROM recurring_rules WHERE id=?',r.id)),date('05'));});
test('Auto rent cannot be increased through rule editor without all residents agreeing',t=>{const f=fixture(t),{l}=setup(f,{auto:true}),r=f.db.get('SELECT * FROM recurring_rules WHERE lease_id=?',l.id);assert.throws(()=>edit(f,r,{effective_month:date('02'),amount:7000000}),status(409));edit(f,r,{effective_month:date('02'),advance_days:30});assert.equal(D.ruleAt(f.db,r,date('02')).advance_days,30);});
test('Two distinct monthly charges may share one month without accidental deduplication',t=>{const f=fixture(t),{l}=setup(f);rule(f,l,{title:'Интернет'});rule(f,l,{title:'Парковка',amount:400000});run(f,date('01-20'));assert.equal(list(f,l).length,2);assert.deepEqual(list(f,l).map(r=>r.payload.amount).sort((a,b)=>a-b),[90000,400000]);});
test('Repeat checkbox creates first bill now and a rule without regenerating that first bill',t=>{const f=fixture(t),{l}=setup(f);const r=f.db.tx(()=>D.createRecord(f.db,f.owner,{lease_id:l.id,kind:'charge',title:'Регулярная услуга',payload:{amount:45000,due:date('01-15'),period:date('01'),repeat:true}},f.config));assert.ok(r.payload.rule_id);run(f,date('01-20'));assert.equal(list(f,l).length,1);run(f,date('02-02'));assert.equal(list(f,l).length,2);});
test('Future charge is cancelled on mutually accepted early termination only when untouched',t=>{const f=fixture(t),l=f.lease,u=f.tenant,ym=D.nextMonth(D.dateInZone().slice(0,7));f.db.tx(()=>D.createRecurringRule(f.db,f.owner,{lease_id:l.id,title:'Будущая услуга',amount:90000,due_day:1,advance_days:60,start_month:ym},f.config));run(f,D.dateInZone());const future=list(f,l).filter(r=>r.payload.period===ym&&r.payload.rule_id);assert.ok(future.length);const end=f.db.tx(()=>D.createRecord(f.db,u,{lease_id:l.id,kind:'termination',title:'Завершение',payload:{date:D.dateInZone(),reason:'Переезд'}},f.config));f.db.tx(()=>D.actionRecord(f.db,f.owner,end.id,{version:end.version,action:'accept'}));for(const r of future)assert.equal(f.db.get('SELECT status FROM records WHERE id=?',r.id).status,'cancelled');});
