import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,newUser,apartmentInput,status,httpFixture} from './helpers.mjs';
import * as D from '../server/domain.mjs';import {createUnit,updateUnit} from '../server/rental.mjs';
import {createSession} from '../server/auth.mjs';
const tx=(f,fn)=>f.db.tx(fn);
const invite=(f,l,u)=>{const i=tx(f,()=>D.createInvite(f.db,f.owner,l.id));tx(f,()=>D.joinInvite(f.db,u,i.code));return i;};
function roomSetup(f){const a=tx(f,()=>D.createApartment(f.db,f.owner,{...apartmentInput,rental_mode:'rooms',unit_title:'Комната А'})),l1=f.db.get('SELECT * FROM leases WHERE apartment_id=?',a.id),unit=tx(f,()=>createUnit(f.db,f.owner,a.id,{title:'Комната Б'})),l2=tx(f,()=>D.createLease(f.db,f.owner,a.id,{...apartmentInput,unit_id:unit.id}));const alice=newUser(f.db,'Алиса'),bob=newUser(f.db,'Борис'),charlie=newUser(f.db,'Вера');invite(f,l1,alice);invite(f,l1,bob);invite(f,l2,charlie);return {a,l1,l2,alice,bob,charlie,unit};}
const create=(f,l,u,kind,payload={})=>tx(f,()=>D.createRecord(f.db,u,{lease_id:l.id,kind,title:'Тест '+kind,payload},f.config));
const act=(f,r,u,action,extra={})=>tx(f,()=>D.actionRecord(f.db,u,r.id,{version:f.db.get('SELECT version FROM records WHERE id=?',r.id).version,action,...extra}));

test('Whole apartment accepts three paying tenants and creates one shared rent bill, not three',t=>{const f=fixture(t),a=tx(f,()=>D.createApartment(f.db,f.owner,apartmentInput)),l=f.db.get('SELECT * FROM leases WHERE apartment_id=?',a.id);const users=[newUser(f.db,'Один'),newUser(f.db,'Два'),newUser(f.db,'Три')];for(const u of users)invite(f,l,u);assert.equal(D.memberIds(f.db,l.id).length,3);tx(f,()=>D.generateRecurring(f.db,f.config));tx(f,()=>D.generateRecurring(f.db,f.config));const charges=f.db.all("SELECT * FROM records WHERE lease_id=? AND kind='charge'",l.id).map(D.decode);assert.ok(charges.length);assert.ok(charges.every(r=>r.payload.amount===apartmentInput.rent));assert.equal(new Set(charges.map(r=>r.payload.period)).size,charges.length);for(const u of users)assert.equal(D.bootstrap(f.db,u,f.config).leases[0].tenant_ids.length,3);});
test('Independent rooms each have their own household and whole-unit option remains present',t=>{const f=fixture(t),x=roomSetup(f);assert.equal(f.db.get("SELECT COUNT(*) n FROM rental_units WHERE apartment_id=?",x.a.id).n,3);assert.deepEqual(D.bootstrap(f.db,x.alice,f.config).leases.map(l=>l.id),[x.l1.id]);assert.deepEqual(D.bootstrap(f.db,x.charlie,f.config).leases.map(l=>l.id),[x.l2.id]);assert.throws(()=>tx(f,()=>D.createLease(f.db,f.owner,x.a.id,apartmentInput)),status(409));assert.throws(()=>tx(f,()=>D.createLease(f.db,f.owner,x.a.id,{...apartmentInput,unit_id:x.unit.id})),status(409));});
test('Room documents, receipts, discussions, events and records are not disclosed to another room',t=>{const f=fixture(t),x=roomSetup(f),r=(()=>{f.db.run('INSERT INTO files VALUES(?,?,?,?,?,?,?,?,?,?)','private-file',x.a.id,x.l1.id,null,x.alice.id,'document.txt','text/plain',1,'private-file',D.nowISO());return tx(f,()=>D.createRecord(f.db,x.alice,{lease_id:x.l1.id,kind:'document',title:'Договор',payload:{category:'contract',description:'private to group'},files:['private-file']},f.config));})();tx(f,()=>D.addComment(f.db,x.bob,r.id,{text:'Только первая комната'}));const s=D.bootstrap(f.db,x.charlie,f.config);assert.ok(!s.records.some(v=>v.id===r.id));assert.ok(!s.comments.some(v=>v.record_id===r.id));assert.ok(!s.files.some(v=>v.id==='private-file'));assert.ok(!s.events.some(v=>v.lease_id===x.l1.id));assert.ok(!s.people.some(v=>v.id===x.alice.id));assert.throws(()=>D.recordAccess(f.db,x.charlie,r.id),status(404));assert.equal(D.recordAccess(f.db,x.bob,r.id).record.id,r.id);});
test('Owner-only financial record stays invisible even to co-tenants',t=>{const f=fixture(t),x=roomSetup(f),r=create(f,x.l1,f.owner,'expense',{amount:100,date:D.dateInZone()});for(const u of [x.alice,x.bob,x.charlie])assert.throws(()=>D.recordAccess(f.db,u,r.id),status(404));});
test('Room editing requires ownership and current version',t=>{const f=fixture(t),x=roomSetup(f);assert.throws(()=>updateUnit(f.db,x.alice,x.unit.id,{version:1,title:'Взлом'}),status(404));assert.equal(updateUnit(f.db,f.owner,x.unit.id,{version:1,title:'С балконом'}).version,2);assert.throws(()=>updateUnit(f.db,f.owner,x.unit.id,{version:1,title:'Старое'}),status(409));assert.throws(()=>updateUnit(f.db,f.owner,x.unit.id,{version:2,title:'Комната А'}),status(409));});
test('Empty lease can be archived, but an occupied lease cannot be silently removed',t=>{const f=fixture(t),a=tx(f,()=>D.createApartment(f.db,f.owner,apartmentInput)),l=f.db.get('SELECT * FROM leases WHERE apartment_id=?',a.id),i=tx(f,()=>D.createInvite(f.db,f.owner,l.id));tx(f,()=>D.archiveDraftLease(f.db,f.owner,l.id));assert.equal(f.db.get('SELECT status FROM leases WHERE id=?',l.id).status,'ended');assert.throws(()=>tx(f,()=>D.joinInvite(f.db,f.other,i.code)),status(400));const unit=tx(f,()=>createUnit(f.db,f.owner,a.id,{title:'Комната'}));const fresh=tx(f,()=>D.createLease(f.db,f.owner,a.id,{...apartmentInput,unit_id:unit.id}));invite(f,fresh,f.other);assert.throws(()=>D.archiveDraftLease(f.db,f.owner,fresh.id),status(409));});
test('Database itself rejects whole/room overlap, not just the HTTP validation',t=>{const f=fixture(t),x=roomSetup(f),whole=f.db.get("SELECT id FROM rental_units WHERE apartment_id=? AND kind='whole'",x.a.id);assert.throws(()=>f.db.run('UPDATE leases SET unit_id=? WHERE id=?',whole.id,x.l1.id),/overlap/);});
test('Independent joint payment claims reserve remaining amount and owner confirms each exactly once',t=>{const f=fixture(t),x=roomSetup(f);let r=create(f,x.l1,f.owner,'charge',{amount:6000000,period:D.dateInZone().slice(0,7),due:D.dateInZone()});r=act(f,r,x.alice,'claim',{amount:2000000});assert.throws(()=>act(f,r,x.alice,'claim',{amount:1}),status(409));assert.throws(()=>act(f,r,x.bob,'claim',{amount:4000001}),status(400));r=act(f,r,x.bob,'claim',{amount:4000000});assert.equal(r.payload.confirmed,0);assert.equal(r.payload.claims.length,2);assert.throws(()=>act(f,r,x.alice,'confirm'),status(403));const first=r.payload.claims[0].id;r=act(f,r,f.owner,'confirm',{claim_id:first});assert.equal(r.payload.confirmed,2000000);assert.equal(r.status,'claimed');assert.throws(()=>act(f,r,f.owner,'confirm',{claim_id:first}),status(409));r=act(f,r,f.owner,'confirm',{claim_id:r.payload.claims[0].id});assert.equal(r.payload.confirmed,6000000);assert.equal(r.status,'paid');assert.deepEqual(new Set(r.payload.payments.map(p=>p.user_id)),new Set([x.alice.id,x.bob.id]));});
test('Rejected payment releases reserved sum, stale version never duplicates it',t=>{const f=fixture(t),x=roomSetup(f);let r=create(f,x.l1,f.owner,'charge',{amount:10000,period:D.dateInZone().slice(0,7),due:D.dateInZone()});const old=r.version;r=act(f,r,x.alice,'claim',{amount:10000});assert.throws(()=>tx(f,()=>D.actionRecord(f.db,x.bob,r.id,{version:old,action:'claim',amount:5000})),status(409));r=act(f,r,f.owner,'reject',{claim_id:r.payload.claims[0].id,note:'Перевод не найден'});assert.equal(r.status,'pending');r=act(f,r,x.bob,'claim',{amount:10000});assert.equal(r.payload.claims[0].user_id,x.bob.id);assert.throws(()=>act(f,r,x.charlie,'claim',{amount:1}),status(404));});
test('Manual payment validates named payer against correct tenancy',t=>{const f=fixture(t),x=roomSetup(f);let r=create(f,x.l1,f.owner,'charge',{amount:10000,period:D.dateInZone().slice(0,7),due:D.dateInZone()});assert.throws(()=>act(f,r,f.owner,'record_payment',{amount:100,payer_id:x.charlie.id}),status(400));r=act(f,r,f.owner,'record_payment',{amount:10000,payer_id:x.bob.id});assert.equal(r.payload.payments[0].user_id,x.bob.id);assert.equal(r.status,'paid');});
test('Ticket needs original reporter confirmation; co-tenant can report persisting problem',t=>{const f=fixture(t),x=roomSetup(f);let r=create(f,x.l1,x.alice,'ticket',{room:'Кухня',description:'Кран',priority:'normal'});r=act(f,r,f.owner,'resolve',{note:'Ремонт выполнен'});assert.equal(r.status,'resolved');assert.throws(()=>act(f,r,f.owner,'confirm'),status(403));assert.throws(()=>act(f,r,x.bob,'confirm'),status(403));r=act(f,r,x.bob,'reopen',{note:'Ещё течёт'});assert.equal(r.status,'in_progress');r=act(f,r,f.owner,'resolve',{note:'Исправили'});r=act(f,r,x.alice,'confirm');assert.equal(r.status,'closed');});
test('All co-tenants agree visit; counterproposal clears old consent',t=>{const f=fixture(t),x=roomSetup(f),times={start:new Date(Date.now()+86400000).toISOString(),end:new Date(Date.now()+90000000).toISOString()};let r=create(f,x.l1,f.owner,'visit',{...times,reason:'Проверка'});r=act(f,r,x.alice,'accept');assert.equal(r.status,'proposed');assert.throws(()=>act(f,r,x.alice,'accept'),status(409));r=act(f,r,x.bob,'accept');assert.equal(r.status,'accepted');r=act(f,r,x.alice,'counter',times);assert.deepEqual(new Set(r.payload.required_approvals),new Set([f.owner.id,x.bob.id]));assert.equal(r.payload.accepted_by.length,0);r=act(f,r,f.owner,'accept');assert.equal(r.status,'counter');r=act(f,r,x.bob,'accept');assert.equal(r.status,'accepted');});
test('Joining household adds required approval to unresolved proposals',t=>{const f=fixture(t),x=roomSetup(f);let r=create(f,x.l1,f.owner,'terms',{rent:6500000,terms:'Новая цена'});r=act(f,r,x.alice,'accept');const next=newUser(f.db,'Ещё один');invite(f,x.l1,next);r=D.decode(f.db.get('SELECT * FROM records WHERE id=?',r.id));assert.ok(r.payload.required_approvals.includes(next.id));r=act(f,r,x.bob,'accept');assert.equal(r.status,'proposed');r=act(f,r,next,'accept');assert.equal(r.status,'accepted');assert.equal(f.db.get('SELECT rent FROM leases WHERE id=?',x.l1.id).rent,6500000);});
test('All participants agree termination before owner can finalize; archive stays accessible',t=>{const f=fixture(t),x=roomSetup(f);let r=create(f,x.l1,x.alice,'termination',{date:D.dateInZone(),reason:'Выезд'});r=act(f,r,f.owner,'accept');assert.equal(r.status,'proposed');r=act(f,r,x.bob,'accept');assert.equal(r.status,'accepted');r=act(f,r,f.owner,'complete');assert.equal(r.status,'completed');assert.equal(D.bootstrap(f.db,x.alice,f.config).leases[0].status,'ended');assert.throws(()=>invite(f,x.l1,newUser(f.db)),status(409));});
test('Apartment-level and room meters coexist; common numeric readings are shared but attachments are not',t=>{const f=fixture(t),x=roomSetup(f);const common=tx(f,()=>D.createMeter(f.db,f.owner,x.l1.id,{label:'Общая вода',kind:'cold_water',unit:'м³',scope:'apartment',baseline:1000})).meters[0];const local=tx(f,()=>D.createMeter(f.db,f.owner,x.l1.id,{label:'Комната А',kind:'electricity',unit:'кВт·ч'})).meters[0];const localB=tx(f,()=>D.createMeter(f.db,f.owner,x.l2.id,{label:'Комната Б',kind:'electricity',unit:'кВт·ч'})).meters[0];const r=create(f,x.l1,x.alice,'reading',{values:[{meter_id:common.id,value:3000},{meter_id:local.id,value:2000}]});const second=D.bootstrap(f.db,x.charlie,f.config);assert.ok(second.meters.some(m=>m.id===common.id));assert.ok(!second.meters.some(m=>m.id===local.id));assert.equal(second.meter_history.find(v=>v.meter_id===common.id).record_id,null);assert.ok(!second.records.some(v=>v.id===r.id));assert.throws(()=>create(f,x.l2,x.charlie,'reading',{values:[{meter_id:common.id,value:5000},{meter_id:localB.id,value:2000}]}),status(400));const r2=create(f,x.l2,x.charlie,'reading',{values:[{meter_id:localB.id,value:2000}]});assert.equal(r2.payload.values.length,1);assert.equal(f.db.get('SELECT value FROM meter_values WHERE meter_id=?',common.id).value,3000);});
test('Configurable channels support duplicate types, gas, heat and arbitrary names, no fixed defaults',t=>{const f=fixture(t),x=roomSetup(f);assert.equal(D.visibleMeters(f.db,x.l1).length,0);for(const [label,kind,unit] of [['Вода 1','hot_water','м³'],['Вода 2','hot_water','м³'],['Газ','gas','м³'],['Тепло','heating','Гкал'],['Свой прибор','other','ед.']])tx(f,()=>D.createMeter(f.db,f.owner,x.l1.id,{label,kind,unit}));const electric=tx(f,()=>D.createMeter(f.db,f.owner,x.l1.id,{label:'Энергия',kind:'electricity',unit:'кВт·ч',scheme:'triple'}));assert.equal(electric.meters.length,3);assert.equal(new Set(electric.meters.map(m=>m.tariff)).size,3);assert.equal(D.visibleMeters(f.db,x.l1).length,8);assert.throws(()=>D.createMeter(f.db,x.alice,x.l1.id,{label:'Запрет'}),status(404));});
test('Added channel can be submitted in same month; disabling preserves history; replacement uses new baseline',t=>{const f=fixture(t),x=roomSetup(f);const m=tx(f,()=>D.createMeter(f.db,f.owner,x.l1.id,{label:'Газ',unit:'м³',kind:'gas'})).meters[0];create(f,x.l1,x.alice,'reading',{values:[{meter_id:m.id,value:2000}]});assert.throws(()=>D.updateMeter(f.db,f.owner,m.id,{baseline:1000}),status(409));tx(f,()=>D.updateMeter(f.db,f.owner,m.id,{active:false,version:m.version}));const next=tx(f,()=>D.createMeter(f.db,f.owner,x.l1.id,{label:'Новый газ',kind:'gas',unit:'м³'})).meters[0];tx(f,()=>D.configureMeters(f.db,f.owner,x.l1.id,{enabled:false}));assert.throws(()=>create(f,x.l1,x.bob,'reading',{values:[{meter_id:next.id,value:1000}]}),status(409));tx(f,()=>D.configureMeters(f.db,f.owner,x.l1.id,{enabled:true}));create(f,x.l1,x.bob,'reading',{values:[{meter_id:next.id,value:1000}]});assert.equal(f.db.get('SELECT COUNT(*) n FROM meter_values WHERE meter_id IN (?,?)',m.id,next.id).n,2);assert.equal(D.bootstrap(f.db,x.alice,f.config).meters.find(v=>v.id===m.id).active,0);});
test('HTTP invitations use bot start, and multiple tenant file routes remain isolated',async t=>{const f=await httpFixture(t);f.config.botUsername='test_bot';await f.login('owner');const result=await f.api('/api/leases/'+f.lease.id+'/invite',{method:'POST',body:{}});assert.equal(result.status,200);assert.ok(result.data.url.includes('?start=join_'));assert.ok(!result.data.url.includes('startapp'));const user=newUser(f.db,'Совместный жилец');tx(f,()=>D.joinInvite(f.db,user,result.data.code));f.setToken(createSession(f.db,user.id).token);const state=await f.api('/api/state');assert.equal(state.status,200);assert.ok(state.data.leases.some(l=>l.tenant_ids.includes(user.id)));assert.equal((await f.api('/api/leases/'+f.lease.id+'/meter-settings',{method:'POST',body:{enabled:false}})).status,404);});
