import {existsSync,readFileSync,mkdirSync,cpSync,renameSync,rmSync,lstatSync} from 'node:fs';import path from 'node:path';import {createHash,randomUUID} from 'node:crypto';import {DatabaseSync} from 'node:sqlite';import {makeConfig} from '../server/config.mjs';
try{
 const fromIndex=process.argv.indexOf('--from');if(fromIndex<0||!process.argv.includes('--stopped')||!process.argv.includes('--confirm'))throw Error('Остановите сервер. Использование: npm run restore -- --from backups/keys-DATE --stopped --confirm');
 const c=makeConfig(),source=path.resolve(process.argv[fromIndex+1]),target=c.dataDir;if(source===target||source.startsWith(target+path.sep))throw Error('Копия должна быть вне DATA_DIR.');
 const manifest=JSON.parse(readFileSync(path.join(source,'manifest.json'),'utf8'));if(manifest.format!==1||!Array.isArray(manifest.files)||!manifest.files.some(f=>f.path==='keys.sqlite'))throw Error('Неизвестный формат копии.');
 if(c.mode==='production'&&manifest.mode!=='production')throw Error('Нельзя восстановить демонстрационную базу в production.');
 for(const f of manifest.files){const p=path.resolve(source,f.path);if(!p.startsWith(source+path.sep)||lstatSync(p).isSymbolicLink())throw Error('Недопустимый путь в manifest');const b=readFileSync(p);if(b.length!==f.size||createHash('sha256').update(b).digest('hex')!==f.sha256)throw Error('Повреждён файл: '+f.path);}
 const stage=target+'.restore-'+randomUUID();mkdirSync(stage,{recursive:true,mode:0o700});try{for(const f of manifest.files){const dest=path.resolve(stage,f.path);if(!dest.startsWith(stage+path.sep))throw Error('Некорректный путь');mkdirSync(path.dirname(dest),{recursive:true});cpSync(path.join(source,f.path),dest);}const db=new DatabaseSync(path.join(stage,'keys.sqlite'));try{if(db.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw Error('Проверка SQLite не пройдена');db.exec('DELETE FROM sessions; DELETE FROM invites; DELETE FROM idempotency; DELETE FROM outbox; DELETE FROM webhook_inbox;');}finally{db.close();}
 if(existsSync(target)){const old=target+'.before-restore-'+Date.now();renameSync(target,old);console.log('Предыдущие данные сохранены:',old);}renameSync(stage,target);console.log('Восстановлено:',target);console.log('Сеансы, приглашения и очереди очищены: старые уведомления не будут отправлены повторно. Перезапустите приложение.');}catch(e){rmSync(stage,{recursive:true,force:true});throw e;}
}catch(e){console.error(e.message);process.exit(1);}
